version: "3"
services:
  api:
    build:
      "./api"
    image: api-campeonato
    container_name: api-campeonato-container
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=app.py
      - APP_ENV=development
    depends_on:
      - db
  db:
    image: mysql-image
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: olamundo
    volumes:
      - ./db/data/:/var/lib/mysql
