version: "3"
services:
  api:
    build:
      "./api"
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=app.py
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: olamundo
    volumes:
      - ./api/db/data/:/var/lib/mysql
